name: dies_und_das
description: Sven's Schweizer Spezialtaschenmesser
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_picker: ^2.1.0
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
